// This must exactly match Backend/utils/industries.js
// Used as fallback if API call fails

export const INDUSTRIES = [
  "Accounting & Auditing",
  "Advertising & Marketing",
  "Agriculture & Agribusiness",
  "Agriculture Technology / AgriTech",
  "Airlines & Aviation",
  "Architecture & Planning",
  "Automotive",
  "Banking",
  "Biotechnology",
  "BPO / KPO / Call Centre",
  "Chemicals & Petrochemicals",
  "Construction & Infrastructure",
  "Consulting",
  "Consumer Durables",
  "Consumer Goods / FMCG",
  "Defence & Aerospace",
  "E-commerce",
  "E-learning",
  "Education & Training",
  "EdTech",
  "Electronics",
  "Energy & Power",
  "Engineering & Industrial",
  "Entertainment & Media",
  "Environmental Services",
  "Event Management",
  "Facility Management",
  "Fashion & Apparel",
  "Financial Services",
  "FinTech",
  "Food & Beverage",
  "Government & Public Sector",
  "Government Services",
  "Healthcare & Hospitals",
  "HealthTech",
  "Hospitality & Hotels",
  "Human Resources & Recruitment",
  "Import & Export",
  "Information Technology & Software",
  "Insurance",
  "Internet & Online Services",
  "Investment Banking",
  "ITES",
  "Jewellery & Gems",
  "Legal Services",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Marine & Shipping",
  "Market Research",
  "Media & Publishing",
  "Medical Devices",
  "Mining & Metals",
  "NBFC",
  "Non-Profit / NGO",
  "Oil & Gas",
  "Pharmaceuticals",
  "Printing & Packaging",
  "Professional Services",
  "PropTech / Real Estate Technology",
  "Railways & Metro",
  "Real Estate",
  "Renewable Energy",
  "Research & Development",
  "Retail",
  "Security Services",
  "Semiconductors",
  "Social Services",
  "Sports & Fitness",
  "Telecommunications",
  "Textile & Garments",
  "Transportation",
  "Travel & Tourism",
  "Wealth Management",
  "Wellness & Personal Care",
  "Wholesale & Distribution",
  "Other",
] as const;

export type Industry = (typeof INDUSTRIES)[number];